from .settings import (
    FEISHU_WEBHOOK_URL,
    FEISHU_SIGNING_KEY,
    FEISHU_AI_WEBHOOK_URL,
    FEISHU_AI_SIGNING_KEY,

    DINGTALK_WEBHOOK_URL,
    DINGTALK_SIGNING_KEY,
    DINGTALK_AI_WEBHOOK_URL,
    DINGTALK_AI_SIGNING_KEY,

    NEWS_API_KEY
)
