# 环境变量获取
import os

FEISHU_WEBHOOK_URL = os.getenv('FEISHU_WEBHOOK_URL', '')
FEISHU_SIGNING_KEY = os.getenv('FEISHU_SIGNING_KEY', '')

FEISHU_AI_WEBHOOK_URL = os.getenv('FEISHU_AI_WEBHOOK_URL', '')
FEISHU_AI_SIGNING_KEY = os.getenv('FEISHU_AI_SIGNING_KEY', '')

DINGTALK_WEBHOOK_URL = os.getenv('DINGTALK_WEBHOOK_URL', '')
DINGTALK_SIGNING_KEY = os.getenv('DINGTALK_SIGNING_KEY', '')

DINGTALK_AI_WEBHOOK_URL = os.getenv('DINGTALK_WEBHOOK_URL', '')
DINGTALK_AI_SIGNING_KEY = os.getenv('DINGTALK_SIGNING_KEY', '')

NEWS_API_KEY = os.getenv('NEWS_API_KEY', '')
